try:
    from env.abstract_classes import Controller
    from env.demand import Demand
except:
    from abstract_classes import Controller
    from demand import Demand
import copy 

class DemandController(Controller):
    def __init__(self, demand_params, time_step):
        """
        Inputs:

            windturbine_params: dictionary with the following keys
                - controller: dictionary with the following keys
                    - const_params: dictionary with the following keys:
                        - power_max: maximal power the wind turbine can generate
                        - power_min: minimal power the wind turbine can generate
                - device: dictionary with the const_params and init_params of the wind turbine simulator
        """


        self.time_step = time_step

        demand_controller_const_params = demand_params['controller']['const_params']
        demand_controller_init_params = demand_params['controller']['init_params']   
        
        # Initializing the simulator
        demand_sim_params = demand_params['device']
        demand_sim_params_dummy = copy.deepcopy(demand_sim_params)
        demand_sim_params_dummy['const_params']['mode'] = {'value': 'dummy', 'type': 'string'}
        
        self.demand_sim = Demand(demand_sim_params_dummy, self.time_step, real = False)


        self.reset(demand_controller_init_params, demand_params['device']['init_params'])



    def reset(self, demand_controller_init_params, demand_sim_init_params):
        """
        Resets the controller to a new episode. Updates the simulator based on the wind turbine's initial parameters.
        """
        # No controller state to reset

        # Resetting the demand
        self.demand_sim.simulator_sensor_update(demand_sim_init_params)

    def update_controller_state(self, observations, next_step=False):
        """
        Updates the simulator based on the observation from the true wind turbine.

        Inputs:
            device_observations is a dictionary with the following keys:
                wind_speed: wind speed in m/s
                power_output: power output of the wind turbine in kW
                temperature: temperature in degrees Celsius
                humidity: humidity in percentage
                wind_direction: wind direction in degrees
        """

        # update simulator parameters
        self.demand_sim.simulator_sensor_update(observations['device_observations'], next_step=next_step)
            
    def simulator_dynamic_update(self, action):
        """
        Updates the simulator based on the action taken by the wind turbine controller.

        Inputs:
            action: action taken by the wind turbine controller
        """
        valid_action = self.generate_safe_action(action)
        self.demand_sim.step(valid_action, verbose = False)
        observations = self.gather_observations()
        return observations

    def check_valid(self, processed_action):
        pass

    def gather_observations(self):
        """
        Gathers the observations from the wind turbine simulator.

        Returns:
            observations: dictionary containing the observations from the wind turbine simulator
        """
        observations = {'device_observations': self.demand_sim.gather_observations(), 'controller_state': {}}

        return observations

    def generate_safe_action(self, action):
        """
        Generates a safe action based on the given action.

        Inputs:
            action: action taken by the wind turbine controller

        Returns:
            safe_action: safe action generated by the wind turbine controller
        """
        safe_action = copy.deepcopy(action)

        return safe_action


    def predict_step(self, action, date_time):
        """
        Predicts the next step of the wind turbine simulator based on the given action.

        Inputs:
            action: action taken by the wind turbine controller

        Returns:
            predicted_power_output: predicted power output of the wind turbine in kW
        """
        #
        # copy_self = copy.deepcopy(self)
        observations_pred = self.simulator_dynamic_update(action, date_time)
        return observations_pred