try:
    from env.abstract_classes import Controller
    from env.windturbine import WindTurbine
except:
    from abstract_classes import Controller
    from windturbine import WindTurbine
import copy 

class WindTurbineController(Controller):
    def __init__(self, windturbine_params, time_step):
        """
        Inputs:

            windturbine_params: dictionary with the following keys
                - controller: dictionary with the following keys
                    - const_params: dictionary with the following keys:
                        - power_max: maximal power the wind turbine can generate
                        - power_min: minimal power the wind turbine can generate
                - device: dictionary with the const_params and init_params of the wind turbine simulator
        """


        self.time_step = time_step

        self.active_turbine = windturbine_params['device']['init_params']['active']['value']

        windturbine_controller_const_params = windturbine_params['controller']['const_params']
        windturbine_controller_init_params = windturbine_params['controller']['init_params']   
        
        if self.active_turbine:
 
            self.power_max = windturbine_controller_const_params['power_max']['value']  # Maximal power the wind turbine can generate
            self.power_min = windturbine_controller_const_params['power_min']['value']  # Minimal power the wind turbine can generate

            self.active_turbine = windturbine_params['device']['init_params']['active']['value']

        # Initializing the simulator
        wind_turbine_sim_const_params = windturbine_params['device']
        windturbine_sim_params_dummy = copy.deepcopy(wind_turbine_sim_const_params)
        if self.active_turbine: 
            windturbine_sim_params_dummy['const_params']['mode'] = {'value': 'dummy', 'type': 'string'}
        self.windturbine_sim = WindTurbine(windturbine_sim_params_dummy, self.time_step, real = False)

        self.reset(windturbine_controller_init_params, windturbine_params['device']['init_params'])



    def reset(self, windturbine_controller_init_params, windturbine_sim_init_params):
        """
        Resets the controller to a new episode. Updates the simulator based on the wind turbine's initial parameters.
        """
        # No controller state to reset

        # Resetting the simulator
        if self.active_turbine:
            self.windturbine_sim.reset(windturbine_sim_init_params)

    def update_controller_state(self, observations, next_step=False):
        """
        Updates the simulator based on the observation from the true wind turbine.

        Inputs:
            device_observations is a dictionary with the following keys:
                wind_speed: wind speed in m/s
                power_output: power output of the wind turbine in kW
                temperature: temperature in degrees Celsius
                humidity: humidity in percentage
                wind_direction: wind direction in degrees
        """

        # update simulator parameters
        if self.active_turbine:
            self.windturbine_sim.simulator_sensor_update(observations['device_observations'], next_step=next_step)
            
    def simulator_dynamic_update(self, action, next_step=False):
        """
        Updates the simulator based on the action taken by the wind turbine controller.

        Inputs:
            action: action taken by the wind turbine controller
        """
        valid_action = self.generate_safe_action(action)
        self.windturbine_sim.step(valid_action, next_step = next_step, verbose = False)
        observations = self.gather_observations()
        return observations

    def check_valid(self, processed_action):
        pass

    def gather_observations(self):
        """
        Gathers the observations from the wind turbine simulator.

        Returns:
            observations: dictionary containing the observations from the wind turbine simulator
        """
        observations = {'device_observations': self.windturbine_sim.gather_observations(), 'controller_state': {}}

        return observations

    def generate_safe_action(self, action):
        """
        Generates a safe action based on the given action.

        Inputs:
            action: action taken by the wind turbine controller

        Returns:
            safe_action: safe action generated by the wind turbine controller
        """
        safe_action = copy.deepcopy(action)

        # Check if the action is within the power limits
        if self.active_turbine:
            safe_action['turbine_setpoint'] = max(min(safe_action['turbine_setpoint'], self.power_max), self.power_min)
        else:
            safe_action['turbine_setpoint'] = 0

        return safe_action

    def get_power_limits(self):
        """
        Returns the power limits of the wind turbine.

        Returns:
            power_min: minimal power the wind turbine can generate
            power_max: maximal power the wind turbine can generate
        """
        return self.power_min, self.power_max

    def predict_step(self, action, next_step = False):
        """
        Predicts the next step of the wind turbine simulator based on the given action.

        Inputs:
            action: action taken by the wind turbine controller

        Returns:
            predicted_power_output: predicted power output of the wind turbine in kW
        """
        #
        # copy_self = copy.deepcopy(self)
        observations_pred = self.simulator_dynamic_update(action, next_step=next_step)

        return observations_pred
